// Generated by CoffeeScript 1.3.1
(function() {
  var hookEditor, repositionEditor, theEditor;

  repositionEditor = function() {
    var h;
    h = $(".editControls").css("height");
    return $("#editor").css("margin-top", h);
  };

  theEditor = null;

  hookEditor = function(sel) {
    theEditor = new Docstrap.Editor(sel);
    return window.theEditor = theEditor;
  };

  $(window).resize(function() {
    return repositionEditor();
  });

  $(document).ready(function() {
    repositionEditor();
    $("#editTools").tab();
    return hookEditor("#editor");
  });

}).call(this);
